### ISSUE TITLE
Cannot specify a portion of my provisioners in two different roles and apply them both

### ISSUE THREAD

**Issue by npwalker** [oscar-stack/vagrant-config_builder#14]
```
---
#roles.yaml
roles:
  master:
    private_networks:
      - ip: '0.0.0.0'
        auto_network: true
    provider:
      type: virtualbox
        customize:
          - [modifyvm, !ruby/sym id, '--memory', 2048]
      synced_folders:
        - host_path:  'puppet'
          guest_path: '/root/puppet'
        - host_path:  'files'
          guest_path: '/var/seteam-vagrant-stack'
     provisioners:
       - type: shell
         inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
       - type: hosts

  master310:
    provisioners:
      - type: pe_bootstrap
        role: :master
        version: '3.1.0'
```
```
---
#vms.yaml
vms:
  - name: "master3.1.0-centos"
    box:  "centos-64-x64-vbox4210-nocm"
    roles: [ "master", "master310" ]
```

Using the above roles.yaml and vms.yaml when the machine boots it does not edit hosts as I would expect since I included it in the provisioners under the master role.

**Comment by Sharpie** [comment]
In config_builder 1.0, provisioners can be named which finally enables this use case:

```yaml
---
roles:

  install_pe:
    provisioners:
      - type: pe_bootstrap
        # New Bit: Give the provisioner a name
        name: 'install pe'
        version: version-a

vms:

  - name: vm-a
    provisioners:
     - type: pe_bootstrap
       # Reference the provisioner by name to override role configuration
       name: 'install pe'
       version: version-b
       answer_extras:
         - q_someanswer=somevalue
    roles:
      - install_pe
```
