### ISSUE TITLE
Provider options should be modeled as an array

### ISSUE THREAD

**Issue by Sharpie** [oscar-stack/vagrant-config_builder#19]
Now that `config_builder` is expanding to support multiple Vagrant providers, it would be nice to specify multiple common provider options in a single role using an array. For example, setting the memory size regardless of whether the VM is running under VirtualBox or VMware fusion:

``` yaml
1gb-memory:
  providers:
    - type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 1024]
    - type: vmware_fusion
      vmx:
        memsize: 1024
```
