### ISSUE TITLE
Nested roles support

### ISSUE THREAD

**Issue by pradels** [oscar-stack/vagrant-config_builder#29]
In some cases can be usefull to assign some roles configuration to another role - add together their functionality.

For example, when I use vagrant-libvirt plugin, there are a lot common arguments, but some arguments are specific depending on the role. Config with nested roles can look like this:

```
roles:
  base:
    providers:
      - type: libvirt
        driver: qemu
        host: localhost
        connect_via_ssh: true
        username: root
        storage_pool_name: default
        nested: true

  puppetmaster:
    providers:
      - type: libvirt
        cpus: 2
        memory: 1024
    roles: base

  puppetagent:
    providers:
      - type: libvirt
        cpus: 1
        memory: 512
    roles: base
```

Thanks
Lukas
