### ISSUE TITLE
Arrays of hashes are improperly handled in the roles file.

### ISSUE THREAD

**Issue by adamcrews** [oscar-stack/vagrant-config_builder#9]
I'm trying to add multiple synced_folders to a machine like this:

```

---
roles:
  bigmem:
    synced_folders: [ {host_path: '../src', guest_path: '/v-src'}, {host_path: '../src2', guest_path: '/v-src2'} ]
    provider:
      type: virtualbox
```

and in my vms.yaml

```

---
vms:
  -
    name: 'test01'
    roles: bigmem
```

If I put the same synced_folders line in the vms.yaml under a node, the multiple shared folders are added to the vm.

The roles parsing seems to flatten the hashes into an array, and cause the error:

```
Bringing machine 'test01' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The host path of the shared folder is missing: ../src2
```

However a single hash in the shared_folders line works fine.
